/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 22-ene-2017 01:58:56 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS senvio_pkenvio_seq
;

DROP SEQUENCE IF EXISTS seventosocial_pkevento_seq
;

DROP SEQUENCE IF EXISTS simgevent_pkimgevent_seq
;

DROP SEQUENCE IF EXISTS simgusuario_pkimgusuario_seq
;

DROP SEQUENCE IF EXISTS sscanner_pkscanner_seq
;

DROP SEQUENCE IF EXISTS susuario_pkusuario_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS senvio CASCADE
;

DROP TABLE IF EXISTS seventosocial CASCADE
;

DROP TABLE IF EXISTS simgevent CASCADE
;

DROP TABLE IF EXISTS simgusuario CASCADE
;

DROP TABLE IF EXISTS sscanner CASCADE
;

DROP TABLE IF EXISTS susuario CASCADE
;

/* Create Tables */

CREATE TABLE senvio
(
	pkenvio integer NOT NULL   DEFAULT NEXTVAL(('"senvio_pkenvio_seq"'::text)::regclass),
	fkevento integer NULL,
	fkusuario integer NULL,
	estado char(1) NULL,
	fechaenvio timestamp NULL
)
;

CREATE TABLE seventosocial
(
	pkevento integer NOT NULL   DEFAULT NEXTVAL(('"seventosocial_pkevento_seq"'::text)::regclass),
	sdescripcion varchar(50) NULL,
	sdireccion varchar(50) NULL,
	sfecha timestamp NULL,
	stelefono varchar(15) NULL,
	sestado char(1) NULL,    -- 	
	smensaje varchar(50) NULL,
	path varchar(25) NULL,
	fkusurio integer NULL
)
;

CREATE TABLE simgevent
(
	pkimgevent integer NOT NULL   DEFAULT NEXTVAL(('"simgevent_pkimgevent_seq"'::text)::regclass),
	fkevent integer NOT NULL,
	path varchar(50) NULL,
	fechaing timestamp NULL
)
;

CREATE TABLE simgusuario
(
	pkimgusuario integer NOT NULL   DEFAULT NEXTVAL(('"simgusuario_pkimgusuario_seq"'::text)::regclass),
	fkusuario integer NOT NULL,
	path varchar(50) NULL,
	fechaing timestamp NULL
)
;

CREATE TABLE sscanner
(
	pkscanner integer NOT NULL   DEFAULT NEXTVAL(('"sscanner_pkscanner_seq"'::text)::regclass),
	fkusuario integer NULL,
	fkimgevent integer NULL,
	estado char(1) NULL,
	fechaing timestamp NULL
)
;

CREATE TABLE susuario
(
	pkusuario integer NOT NULL   DEFAULT NEXTVAL(('"susuario_pkusuario_seq"'::text)::regclass),
	snombre varchar(50) NULL,    -- 
	sapellido varchar(50) NULL,
	semail varchar(25) NULL,    -- 
	stelefono varchar(15) NULL,
	spassword varchar(50) NULL,
	stipousuario smallint NULL,
	sestado char(1) NULL,
	username varchar(25) NULL,
	authkey varchar(50) NULL,
	accesstoken varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE senvio ADD CONSTRAINT PK_senvio
	PRIMARY KEY (pkenvio)
;

CREATE INDEX IXFK_senvio_seventosocial ON senvio (fkevento ASC)
;

CREATE INDEX IXFK_senvio_susuario ON senvio (fkusuario ASC)
;

ALTER TABLE seventosocial ADD CONSTRAINT PK_seventosocial
	PRIMARY KEY (pkevento)
;

CREATE INDEX IXFK_seventosocial_susuario ON seventosocial (fkusurio ASC)
;

ALTER TABLE simgevent ADD CONSTRAINT PK_simgscr
	PRIMARY KEY (pkimgevent)
;

CREATE INDEX IXFK_simgevent_seventosocial ON simgevent (fkevent ASC)
;

ALTER TABLE simgusuario ADD CONSTRAINT PK_simgusuario
	PRIMARY KEY (pkimgusuario)
;

CREATE INDEX IXFK_simgusuario_susuario ON simgusuario (fkusuario ASC)
;

ALTER TABLE sscanner ADD CONSTRAINT PK_sscanner
	PRIMARY KEY (pkscanner)
;

CREATE INDEX IXFK_sscanner_susuario ON sscanner (fkusuario ASC)
;

ALTER TABLE susuario ADD CONSTRAINT PK_susuario
	PRIMARY KEY (pkusuario)
;

/* Create Foreign Key Constraints */

ALTER TABLE senvio ADD CONSTRAINT FK_senvio_seventosocial
	FOREIGN KEY (fkevento) REFERENCES seventosocial (pkevento) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE senvio ADD CONSTRAINT FK_senvio_susuario
	FOREIGN KEY (fkusuario) REFERENCES susuario (pkusuario) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE seventosocial ADD CONSTRAINT FK_seventosocial_susuario
	FOREIGN KEY (fkusurio) REFERENCES susuario (pkusuario) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE simgevent ADD CONSTRAINT FK_simgevent_seventosocial
	FOREIGN KEY (fkevent) REFERENCES seventosocial (pkevento) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE simgusuario ADD CONSTRAINT FK_simgusuario_susuario
	FOREIGN KEY (fkusuario) REFERENCES susuario (pkusuario) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sscanner ADD CONSTRAINT FK_sscanner_simgusuario
	FOREIGN KEY (fkimgevent) REFERENCES simgevent (pkimgevent) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sscanner ADD CONSTRAINT FK_sscanner_susuario
	FOREIGN KEY (fkusuario) REFERENCES susuario (pkusuario) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE senvio_pkenvio_seq INCREMENT 1 START 1
;

COMMENT ON COLUMN seventosocial.sestado
	IS '		'
;

CREATE SEQUENCE seventosocial_pkevento_seq INCREMENT 1 START 1
;

CREATE SEQUENCE simgevent_pkimgevent_seq INCREMENT 1 START 1
;

CREATE SEQUENCE simgusuario_pkimgusuario_seq INCREMENT 1 START 1
;

CREATE SEQUENCE sscanner_pkscanner_seq INCREMENT 1 START 1
;

COMMENT ON COLUMN susuario.snombre
	IS '	'
;

COMMENT ON COLUMN susuario.semail
	IS '	'
;

CREATE SEQUENCE susuario_pkusuario_seq INCREMENT 1 START 1
;
