/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 14-Sep-2017 05:50:22 a.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS seventosocial_pkevento_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS seventosocial CASCADE
;

/* Create Tables */

CREATE TABLE seventosocial
(
	pkevento integer NOT NULL   DEFAULT NEXTVAL(('"seventosocial_pkevento_seq"'::text)::regclass),
	sdescripcion varchar(50) NULL,
	sdireccion varchar(50) NULL,
	sfecha timestamp NULL,
	stelefono varchar(15) NULL,
	sestado char(1) NULL,    --         
	smensaje varchar(50) NULL,
	path varchar(25) NULL,
	fkusuario integer NULL,
	fktipoevento smallint NULL,
	sprecioxfoto decimal(10,2) NOT NULL   DEFAULT 1
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE seventosocial ADD CONSTRAINT PK_seventosocial
	PRIMARY KEY (pkevento)
;

CREATE INDEX IXFK_seventosocial_stipoevento ON seventosocial (fktipoevento ASC)
;

CREATE INDEX IXFK_seventosocial_susuario ON seventosocial (fkusuario ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE seventosocial ADD CONSTRAINT FK_seventosocial_stipoevento
	FOREIGN KEY (fktipoevento) REFERENCES stipoevento (pktipoevento) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE seventosocial ADD CONSTRAINT FK_seventosocial_susuario
	FOREIGN KEY (fkusuario) REFERENCES susuario (pkusuario) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN seventosocial.sestado
	IS '        '
;

CREATE SEQUENCE seventosocial_pkevento_seq INCREMENT 1 START 1
;
