/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 29-abr.-2017 2:37:16 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS seventosocial_pkevento_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS seventosocial CASCADE
;

/* Create Tables */

CREATE TABLE seventosocial
(
	pkevento integer NOT NULL   DEFAULT NEXTVAL(('"seventosocial_pkevento_seq"'::text)::regclass),
	sdescripcion varchar(50),
	sdireccion varchar(50),
	sfecha timestamp,
	stelefono varchar(15),
	sestado char(1),    -- 	
	smensaje varchar(50),
	path varchar(25),
	fkusuario integer,
	fktipoevento smallint
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE seventosocial ADD CONSTRAINT PK_seventosocial
	PRIMARY KEY (pkevento)
;

CREATE INDEX IXFK_seventosocial_stipoevento ON seventosocial (fktipoevento ASC)
;

CREATE INDEX IXFK_seventosocial_susuario ON seventosocial (fkusuario ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE seventosocial ADD CONSTRAINT FK_seventosocial_stipoevento
	FOREIGN KEY (fktipoevento) REFERENCES stipoevento (pktipoevento) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE seventosocial ADD CONSTRAINT FK_seventosocial_susuario
	FOREIGN KEY (fkusuario) REFERENCES susuario (pkusuario) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN seventosocial.sestado
	IS '		'
;

CREATE SEQUENCE seventosocial_pkevento_seq INCREMENT 1 START 1
;
