/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 18-Sep-2017 04:35:29 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS simgevent_pkimgevent_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS simgevent CASCADE
;

/* Create Tables */

CREATE TABLE simgevent
(
	pkimgevent integer NOT NULL   DEFAULT NEXTVAL(('"simgevent_pkimgevent_seq"'::text)::regclass),
	fkevent integer NOT NULL,
	path varchar(50) NULL,
	fechaing timestamp NULL,
	estado char(1) NULL,
	idImageCloud varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE simgevent ADD CONSTRAINT PK_simgscr
	PRIMARY KEY (pkimgevent)
;

CREATE INDEX IXFK_simgevent_seventosocial ON simgevent (fkevent ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE simgevent ADD CONSTRAINT FK_simgevent_seventosocial
	FOREIGN KEY (fkevent) REFERENCES seventosocial (pkevento) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE simgevent_pkimgevent_seq INCREMENT 1 START 1
;
