/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 07-Oct-2017 03:21:01 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS simgusuario_pkimgusuario_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS simgusuario CASCADE
;

/* Create Tables */

CREATE TABLE simgusuario
(
	pkimgusuario integer NOT NULL   DEFAULT NEXTVAL(('"simgusuario_pkimgusuario_seq"'::text)::regclass),
	fkusuario integer NOT NULL,
	path varchar(50) NULL,
	fechaing timestamp NULL,
	estado char(1) NULL,
	idImageCloud varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE simgusuario ADD CONSTRAINT PK_simgusuario
	PRIMARY KEY (pkimgusuario)
;

CREATE INDEX IXFK_simgusuario_susuario ON simgusuario (fkusuario ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE simgusuario ADD CONSTRAINT FK_simgusuario_susuario
	FOREIGN KEY (fkusuario) REFERENCES susuario (pkusuario) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE simgusuario_pkimgusuario_seq INCREMENT 1 START 1
;
