/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 29-abr.-2017 11:46:51 a. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS susuario_pkusuario_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS susuario CASCADE
;

/* Create Tables */

CREATE TABLE susuario
(
	pkusuario integer NOT NULL   DEFAULT NEXTVAL(('"susuario_pkusuario_seq"'::text)::regclass),
	snombre varchar(50),    -- 
	sapellido varchar(50),
	semail varchar(25),    -- 
	stelefono varchar(15),
	spassword varchar(50),
	stipousuario smallint,
	sestado char(1),
	username varchar(25),
	authkey varchar(50),
	accesstoken varchar(50)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE susuario ADD CONSTRAINT PK_susuario
	PRIMARY KEY (pkusuario)
;

CREATE INDEX IXFK_susuario_stipousuario ON susuario (stipousuario ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE susuario ADD CONSTRAINT FK_susuario_stipousuario
	FOREIGN KEY (stipousuario) REFERENCES stipousuario (pktipousuario) ON DELETE No Action ON UPDATE No Action;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN susuario.snombre
	IS '	'
;

COMMENT ON COLUMN susuario.semail
	IS '	'
;

CREATE SEQUENCE susuario_pkusuario_seq INCREMENT 1 START 1
;
