/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 29-abr.-2017 2:23:15 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS stipoevento_pktipoevento_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS stipoevento CASCADE
;

/* Create Tables */

CREATE TABLE stipoevento
(
	pktipoevento smallint NOT NULL   DEFAULT NEXTVAL(('"stipoevento_pktipoevento_seq"'::text)::regclass),
	codigo char(3),
	descripcion varchar(25)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE stipoevento ADD CONSTRAINT PK_stipoevento
	PRIMARY KEY (pktipoevento)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE stipoevento_pktipoevento_seq INCREMENT 1 START 1
;
